AWSTemplateFormatVersion: '2010-09-09'
Description: 'EC2, Launch Template, Auto Scaling, and ALB.'

Parameters:
  PublicSubnet1Id:
    Type: String
  PublicSubnet2Id:
    Type: String
  SecurityGroupId:
    Type: String

Resources:
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        ImageId: ami-0727cf12519cc2b5b
        InstanceType: t2.medium
        SecurityGroupIds:
          - !Ref SecurityGroupId
        UserData:
          Fn::Base64: |
            #!/bin/bash
            yum update -y
            yum install -y nginx nodejs
            systemctl start nginx
            systemctl enable nginx

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      MinSize: 2
      MaxSize: 5
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      VPCZoneIdentifier:
        - !Ref PublicSubnet1Id
        - !Ref PublicSubnet2Id

Outputs:
  AutoScalingGroupId:
    Value: !Ref AutoScalingGroup